# Entry index 0
[[Entry]]

name = "ax_utility_lib"
source_directory = "D:/ax_project/ax_virt_layer_utils/utils/ax_utility_lib/src"
output_directory = "D:/ax_project/ax_virt_layer_utils/utils/ax_utility_lib/build/WIN_UM/"

#
#	Input of every pipeline is the output of the previous step.
# 	That doesn`t apply to the first step, and it`s input is nil. (for now)
#
#	Pipeline can hold up to 255 steps
#
[[Entry.Pipeline]]
command = "clang" 			# The main exection command
command_policy_alias = "llvm-clang" 	# The known toolchain specific execution policy alias
command_policy_name = "MyCompile" 	# Toolchain policy name
#
# 	Usage of these properties may differ depending on
#	the policy file and name and their implementations
#
flags = [
	"m64",
	"Wno-deprecated-declarations",
	"std=c23",
	"mavx2",
	"mbmi2",
]
definitions = [
	"AX_UM",
	"AX_WIN64",
]
hooks = [
	"D:/ax_project/ax_virt_layer_utils/utils/ax_utility_lib/src/",
	"D:/ax_project/ax_virt_layer_utils/utils/ax_utility_lib/src/ext",
	"D:/ax_project/ax_virt_layer_utils/utils/ax_utility_lib/src/io",
	"D:/ax_project/ax_virt_layer_utils/utils/ax_utility_lib/src/data",
	"C:/msys64/ucrt64/include",
]

[[Entry.Pipeline]]
command = "ar" 				# The main exection command
command_policy_alias = "llvm-ar" 	# The known toolchain specific execution policy alias
command_policy_name = "MyLib" 		# Toolchain policy name

