[Policies]

[Policies.MyCompile]
function = "Compile"

[Policies.MyLink]
function = "Link"
vars = {
	"output_name" = "myoutput",
	"output_ext" = "exe",
}

[Policies.AX_VIRT_LAYER_LINK]
function = "Link"
vars = {
	"output_name" = "ax_virt_layer",
	"output_ext" = "exe",
}

